#!/usr/bin/env ruby
# encoding: UTF-8

# set the working directory
Dir.chdir ::File.expand_path(File.join(__FILE__, '..'))
# load the website-app
load ::File.expand_path(File.join('..', 'website.rb'), __FILE__)
# Iodine options
Iodine::DEFAULT_HTTP_ARGS[:public] = Root.join('public').to_s
Iodine::DEFAULT_HTTP_ARGS[:log] = true
Iodine.threads ||= 16
